services:
  runner:
    build: &runner-build
      context: .
      platforms:
        - linux/amd64
        #- linux/arm64
      target: runner
      tags:
        - git.grey.ooo/actions/runner:latest
        #- git.grey.ooo/grey.ooo/ga-runner:latest
        #- matthewbaggett/act-runner:latest
    image: git.grey.ooo/actions/runner:latest
  embedded-runner:
    build:
      <<: *runner-build
      target: embedded-runner
      tags:
        - git.grey.ooo/actions/runner:embedded
    image: git.grey.ooo/actions/runner:embedded
