name: Build

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Builder
    runs-on: ubuntu-latest
    container: git.grey.ooo/actions/runner
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
      packages: write # For pushing images to GHCR
    steps:
      - name: "Checkout"
        uses: https://git.grey.ooo/actions/checkout@v5

      - name: "Docker login"
        uses: https://git.grey.ooo/actions/login-action@v3
        with:
          registry: git.grey.ooo
          username: ${{ secrets.GREYOOO_USER || github.actor }}
          password: ${{ secrets.GREYOOO_PAT || secrets.GITHUB_TOKEN }}

      - name: "Set up Docker Buildx"
        uses: https://git.grey.ooo/actions/setup-buildx-action@v3

      - name: "Bake Images"
        uses: https://git.grey.ooo/actions/bake-action@v6
        with:
          source: .
          push: false
          set: |
            *runner*.args.http_proxy=${{ secrets.HTTP_PROXY || '' }}
            *runner*.args.https_proxy=${{ secrets.HTTP_PROXY || '' }}

      - name: "Push images"
        uses: https://git.grey.ooo/actions/bake-action@v6
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          source: .
          push: true
          set: |
            *runner*.args.http_proxy=${{ secrets.HTTP_PROXY || '' }}
            *runner*.args.https_proxy=${{ secrets.HTTP_PROXY || '' }}